development:
  adapter: postgresql
  encoding: unicode
  database: pb_dev
  pool: 5
  username: pflegebot
  password: pflegebot
  host: 127.0.0.1
  port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  database: pb_test
  pool: 5
  username: pflegebot
  password: pflegebot
  host: 127.0.0.1
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: pb_prod
  pool: 10
  username: pflegebot
  password: pflegebot
  host: pbpg
  port: 5432

