# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bunny'
gem 'facebook-messenger'
gem 'puma'
gem 'rack'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rubocop'
end
